# Generated by Django 2.1.1 on 2018-09-18 07:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.TextField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('State', models.CharField(max_length=20)),
                ('Zip_code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{1, 10}$')])),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=120)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('relationship', models.CharField(blank=True, choices=[('W', 'Wife'), ('OC', 'Own-child'), ('H', 'Husband'), ('NIF', 'Not-in-family'), ('OR', 'Other-relative'), ('U', 'Unmarried')], max_length=30, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Address')),
            ],
        ),
    ]
