# Generated by Django 2.1.1 on 2018-09-18 08:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20180918_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='Zip_code',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator('^\\d{ 6 }$')]),
        ),
    ]
